version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deploy/dockerfiles/app.dockerfile
    restart: always
    ports:
    - 3000:3000
    entrypoint: yarn dev --host 0.0.0.0 --port 3000
