version: "3.8"

services:
  app:
    entrypoint: yarn build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/avacoin-frontend:master-latest
    volumes:
      - ./.env.app:/app/.env
      - ./dist:/app/dist
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  